# Generated by Django 5.2.4 on 2025-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=60, null=True)),
                ('modelo', models.CharField(blank=True, max_length=51, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
