# Generated by Django 5.2.1 on 2025-09-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Informe a identificação da categoria', max_length=100, unique=True, verbose_name='Identificacao')),
                ('descricao', models.TextField(default='N/A', help_text='Informe a descrição da categoria', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Protuto_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Informe a identificação da tag', max_length=100, unique=True, verbose_name='Identificacao')),
                ('descricao', models.TextField(default='N/A', help_text='Informe a descrição da categoria', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100, verbose_name='Nome do produto')),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço de venda do produto', max_digits=10, verbose_name='Preço')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='Quantidade do produto em estoque', verbose_name='Qt de produtos')),
                ('disponivel', models.BooleanField(default=True, help_text='Indica se o produto está disponível para venda', verbose_name='Produto Disponivel')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem de exibição do produto', null=True, upload_to='produtos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoria')),
                ('tag', models.ManyToManyField(related_name='produto_tags', to='estoque.protuto_tag')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
