# Generated by Django 5.2.4 on 2025-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(default='000.000.000-00', help_text='CPF no formato 000.000.000-00', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tel_celular',
            field=models.CharField(blank=True, help_text='Telefone celular com DDD', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tel_fixo',
            field=models.CharField(blank=True, help_text='Telefone fixo com DDD', max_length=15, null=True),
        ),
    ]
