# Generated by Django 5.2.4 on 2025-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_cpf_perfil_tel_celular_perfil_tel_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='desafio_pergunta',
            field=models.CharField(blank=True, help_text='Pergunta de recuperação de senha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='desafio_resposta',
            field=models.CharField(blank=True, help_text='Resposta da pergunta de segurança', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True),
        ),
    ]
