# Generated by Django 5.2.4 on 2025-09-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfil_desafio_pergunta_perfil_desafio_resposta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
