# Generated by Django 5.2.4 on 2025-09-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
