# Generated by Django 5.2.4 on 2025-09-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_perfil_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
